name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cargo fmt
        run: cargo fmt --all -- --check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: install libraries
        run: |
          sudo apt update 
          sudo apt install -y libfontconfig1-dev

      - name: Cargo test
        run: cargo test --all
